pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    # embedding: pyannote/wespeaker-voxceleb-resnet34-LM # If you want to use the HF model
    embedding: pyannote_model_wespeaker-voxceleb-resnet34-LM.bin # If you want to use the local model
    embedding_batch_size: 1 # changed from 32 to 1
    embedding_exclude_overlap: true
    # segmentation: pyannote/segmentation-3.0 # If you want to use the HF model
    segmentation: pyannote_model_segmentation-3.0.bin  # If you want to use the local model
    segmentation_batch_size: 32

params:
  clustering:
    method: centroid
    min_cluster_size: 12
    threshold: 0.7045654963945799
  segmentation:
    min_duration_off: 0.0
