# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python poc-tldw

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

permissions:
  contents: read

jobs:
  build-and-run-tests:

    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./PoC_Version

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }} # Adjust if requirements.txt is not at root
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev python3-all-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock
        sudo apt install portaudio19-dev python3-all-dev
        
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip check
    - name: Test ChromaDB lib functions with pytest
      run: |
        pytest PoC_Version/Tests/ChromaDB/test_chromadb.py -v

    - name: Test RAG lib functions with pytest
      run: |
        pytest PoC_Version/Tests/RAG/test_RAG_Library_2.py -v
        pytest PoC_Version/Tests/RAG/test_enhanced_rag_pipeline.py -v

    - name: Test RAG Notes functions with pytest
      run: |
        pytest PoC_Version/Tests/RAG_QA_Chat/test_notes_search.py -v

    - name: Test SQLite lib functions with pytest
      run: |
        # This runs all tests in the PoC_Version/Tests/SQLite_DB directory
        pytest PoC_Version/Tests/SQLite_DB/ -v

    - name: Test Utils lib functions with pytest
      run: |
        pytest PoC_Version/Tests/Utils/test_utils.py -v

    - name: Test Character Chat Library functions with pytest
      run: |
        pytest PoC_Version/Tests/Character_Chat/test_character_chat.py -v

    - name: Test tldw summarize script (example run)
      working-directory: ./PoC_Version
      run: |
        python summarize.py -h