---
name: Python tldw
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
permissions:
  contents: read
jobs:
  build-and-run-tests-latest:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./tldw_Server_API
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock
          sudo apt install portaudio19-dev python3-all-dev
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r tldw_Server_API/requirements.txt
          pip check
      - name: Test Media Versioning Functions/Endpoints with pytest
        run: |
          pwd
          cd ./tldw_Server_API/tests/Media_Ingestion_Modification/
          pytest -s test_media_versions.py
      - name: Test Media Processing Endpoint functions with pytest
        run: |
          pwd
          cd ./tldw_Server_API/tests/Media_Ingestion_Modification/
          pytest -s test_media_processing.py
      - name: Test tldw runs
        run: |
          pwd
           uvicorn tldw_Server_API.app.main:app 
